FROM mysql:8.0
EXPOSE 3306
#COPY ./__database__/migrations/ /home/database/
#COPY ./__database__/init_database.sh /docker-entrypoint-initdb.d/init_database.sh
#RUN chmod +x /docker-entrypoint-initdb.d/init_database.sh